//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\jonas.VERTEXCG\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://vertexcg-sandbox.api.crm.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"Scantegra.Core.Entities" /out:"F:\scantegra\Entity Generation\CrmSvcUtil Ref\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"jonas@vertexcg.com" /password:"*************" 
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Scantegra.Core.Entities
{
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public partial class ScantegraServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public ScantegraServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Scantegra.Core.Entities.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Scantegra.Core.Entities.Account> AccountSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Scantegra.Core.Entities.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Scantegra.Core.Entities.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Scantegra.Core.Entities.Contact> ContactSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Scantegra.Core.Entities.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Scantegra.Core.Entities.msdyn_customerasset"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Scantegra.Core.Entities.msdyn_customerasset> msdyn_customerassetSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Scantegra.Core.Entities.msdyn_customerasset>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Scantegra.Core.Entities.scan_scantegrasettings"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Scantegra.Core.Entities.scan_scantegrasettings> scan_scantegrasettingsSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Scantegra.Core.Entities.scan_scantegrasettings>();
			}
		}

        /// <summary>
		/// Gets a binding to the set of all <see cref="Scantegra.Core.Entities.scan_alert"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Scantegra.Core.Entities.scan_alert> scan_alertSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<Scantegra.Core.Entities.scan_alert>();
            }
        }

        /// <summary>
		/// Gets a binding to the set of all <see cref="Scantegra.Core.Entities.scan_alertnotificationaction"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Scantegra.Core.Entities.scan_alertnotificationaction> scan_alertnotificationactionSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<Scantegra.Core.Entities.scan_alertnotificationaction>();
            }
        }

        /// <summary>
		/// Gets a binding to the set of all <see cref="Scantegra.Core.Entities.scan_alertnotificationgroup"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Scantegra.Core.Entities.scan_alertnotificationgroup> scan_alertnotificationgroupSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<Scantegra.Core.Entities.scan_alertnotificationgroup>();
            }
        }

        /// <summary>
		/// Gets a binding to the set of all <see cref="Scantegra.Core.Entities.scan_alertgroupalertnotificationassociation"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Scantegra.Core.Entities.scan_alertgroupalertnotificationassociation> scan_alertgroupalertnotificationassociationSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<Scantegra.Core.Entities.scan_alertgroupalertnotificationassociation>();
            }
        }
    }
	
	internal sealed class EntityOptionSetEnum
	{
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public static System.Nullable<int> GetEnum(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName)
		{
			if (entity.Attributes.ContainsKey(attributeLogicalName))
			{
				Microsoft.Xrm.Sdk.OptionSetValue value = entity.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>(attributeLogicalName);
				if (value != null)
				{
					return value.Value;
				}
			}
			return null;
		}
	}
}