//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scantegra.Core.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum BookableResource_ResourceType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Account = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contact = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Crew = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Equipment = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Facility = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Generic = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pool = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 3,
	}
}