//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scantegra.Core.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum Connection_Record2ObjectTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Account = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Activity = 4200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agreement = 10117,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementBookingDate = 10118,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementBookingIncident = 10119,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementBookingProduct = 10120,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementBookingService = 10121,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementBookingServiceTask = 10122,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementBookingSetup = 10123,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementInvoiceDate = 10124,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementInvoiceProduct = 10125,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementInvoiceSetup = 10126,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Alert = 10197,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approval = 10039,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BookingAlert = 10014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BookingAlertStatus = 10015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BookingRule = 10017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BookingTimestamp = 10129,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Campaign = 4400,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CampaignActivity = 4402,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Case = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChannelAccessProfileRule = 9400,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CommunicationCircuit = 10202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Competitor = 123,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contact = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contract = 1010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerAsset = 10134,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entitlement = 9700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntitlementChannel = 9701,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntitlementTemplateChannel = 9703,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FacilityEquipment = 4000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fax = 4204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Goal = 9600,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncidentTypeCharacteristic = 10139,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncidentTypeProduct = 10140,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncidentTypeService = 10141,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InventoryAdjustment = 10143,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InventoryAdjustmentProduct = 10144,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InventoryJournal = 10145,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InventoryTransfer = 10146,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invoice = 1090,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticle = 9953,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeBaseRecord = 9930,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lead = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Letter = 4207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MarketingList = 4300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Opportunity = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Order = 1088,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Payment = 10151,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PaymentDetail = 10152,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PaymentMethod = 10153,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PaymentTerm = 10154,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Position = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostalCode = 10155,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PriceList = 1022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProcessNotes = 10075,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProcessSession = 4710,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Product = 1024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProductInventory = 10156,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProfileAlbum = 10008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Project = 10076,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProjectTeamMember = 10084,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PurchaseOrder = 10157,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PurchaseOrderBill = 10158,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PurchaseOrderProduct = 10159,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PurchaseOrderReceipt = 10160,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PurchaseOrderReceiptProduct = 10161,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PurchaseOrderSubStatus = 10162,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quote = 1084,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuoteBookingIncident = 10163,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuoteBookingProduct = 10164,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuoteBookingService = 10165,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuoteBookingServiceTask = 10166,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringAppointment = 4251,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ResourceGroup = 4007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ResourceRestriction_Deprecated = 10191,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ResourceTerritory = 10030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RMA = 10171,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RMAProduct = 10172,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RMAReceipt = 10173,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RMAReceiptProduct = 10174,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RMASubStatus = 10175,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RTV = 10176,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RTVProduct = 10177,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RTVSubStatus = 10178,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SchedulingGroup = 4005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceActivity = 4214,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ShipVia = 10180,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SocialActivity = 4216,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SocialProfile = 99,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemUserSchedulerSetting = 10033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TaxCode = 10181,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Team = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Territory = 2013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TimeGroup = 10034,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TimeGroupDetail = 10035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TimeOffRequest = 10183,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Warehouse = 10185,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrder = 10186,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderCharacteristic_Deprecated = 10187,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderIncident = 10189,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderProduct = 10190,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderService = 10192,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderServiceTask = 10193,
	}
}