//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scantegra.Core.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum QueueItem_ObjectTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Activity = 4200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementBookingDate = 10118,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementBookingSetup = 10123,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementInvoiceDate = 10124,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementInvoiceSetup = 10126,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approval = 10039,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BookingAlert = 10014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CampaignActivity = 4402,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CampaignResponse = 4401,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Case = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fax = 4204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InventoryAdjustment = 10143,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InventoryTransfer = 10146,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticle = 9953,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Letter = 4207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Project = 10076,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProjectTask = 10081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuickCampaign = 4406,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringAppointment = 4251,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ResourceRequest = 10098,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceActivity = 4214,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SocialActivity = 4216,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TimeGroup = 10034,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TimeGroupDetail = 10035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrder = 10186,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderIncident = 10189,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderService = 10192,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderServiceTask = 10193,
	}
}