//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scantegra.Core.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum scan_AlertNotificationActionType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CreateCase = 762390000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CreateWorkOrder = 762390001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 762390003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExecuteRunbook = 762390006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Item = 762390007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Phone = 762390005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostToMicrosoftTeams = 762390002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SMS = 762390004,
	}
}