//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scantegra.Core.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum scan_communicationcircuit_scan_CircuitType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Internet = 762390000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MPLS = 762390001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P2P = 762390002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PRI = 762390004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SIP = 762390003,
	}
}